[package]
name = "shared_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
itertools = "0.10.3"
rand = "0.8.5"

[profile.release-with-debug]
inherits = "release"
debug = true
